- name: download kube-controller-manager binary
  become: yes
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v1.18.6/bin/linux/arm64/kube-controller-manager
    dest: /usr/local/bin/
    mode: 755

- name: Copy kubeconfig files
  become: yes
  copy:
    src: kubeconfig/{{ item }}
    dest: /var/lib/kubernetes/
  with_items:
    - kube-controller-manager.kubeconfig

- name: Put kube-controller-manager.service
  become: yes
  template:
    src: kube-controller-manager.service.j2
    dest: /etc/systemd/system/kube-controller-manager.service

- name: Start kube-controller-manager daemon
  become: yes
  systemd:
    name: kube-controller-manager
    enabled: yes
    state: restarted
    daemon_reload: yes
