- name: download kube-apiserver binary
  become: yes
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v1.18.6/bin/linux/arm64/kube-apiserver
    dest: /usr/local/bin/
    mode: 755

- name: Make folders
  become: yes
  command: mkdir -p /etc/kubernetes/config /var/lib/kubernetes

- name: Copy cert files
  become: yes
  copy:
    src: cert/{{ item }}
    dest: /var/lib/kubernetes/
  with_items:
    - ca.pem
    - ca-key.pem
    - kubernetes-key.pem
    - kubernetes.pem
    - service-account-key.pem
    - service-account.pem

- name: Copy encryption-config files
  become: yes
  copy:
    src: encryption-config.yaml
    dest: /var/lib/kubernetes/

- name: Put kube-apiserver.service
  become: yes
  template:
    src: kube-apiserver.service.j2
    dest: /etc/systemd/system/kube-apiserver.service

- name: Start kube-apiserver daemon
  become: yes
  systemd:
    name: kube-apiserver
    enabled: yes
    state: restarted
    daemon_reload: yes
