- name: make cni/bin directory
  become: yes
  file:
    path: /opt/cni/bin
    state: directory

- name: unarchive cni-plugins
  become: yes
  unarchive:
    src: cni-plugins-linux-arm64-v0.8.6.tgz
    dest: /opt/cni/bin/

- name: copy crictl
  become: yes
  copy:
    src: crictl
    dest: /usr/local/bin/
    mode: 755

- name: download kubelet binary
  become: yes
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v1.18.6/bin/linux/arm64/kubelet
    dest: /usr/local/bin/
    mode: 755

- name: install container runtime
  become: yes
  apt:
    name:
      - containerd
      - runc

- name: Copy cert files
  become: yes
  copy:
    src: cert/{{ item }}
    dest: /var/lib/kubelet/
  with_items:
    - "{{ hostname }}-key.pem"
    - "{{ hostname }}.pem"

- name: Copy kubeconfig files
  become: yes
  copy:
    src: kubeconfig/{{ item }}
    dest: /var/lib/kubelet/kubeconfig
  with_items:
    - "{{ hostname }}.kubeconfig"

- name: make cni/net.d directory
  become: yes
  file:
    path: /etc/cni/net.d
    state: directory

- name: Put 10-bridge.conf
  become: yes
  template:
    src: 10-bridge.conf.j2
    dest: /etc/cni/net.d/10-bridge.conf

- name: Put 99-loopback.conf
  become: yes
  template:
    src: 99-loopback.conf.j2
    dest: /etc/cni/net.d/99-loopback.conf

- name: make etc/containerd directory
  become: yes
  file:
    path: /etc/containerd
    state: directory

- name: Put config.toml
  become: yes
  template:
    src: config.toml.j2
    dest: /etc/containerd/config.toml

- name: Put kubelet-config.yaml
  become: yes
  template:
    src: kubelet-config.yaml.j2
    dest: /var/lib/kubelet/kubelet-config.yaml

- name: Put kubelet.service
  become: yes
  template:
    src: kubelet.service.j2
    dest: /etc/systemd/system/kubelet.service

- name: Start kubelet daemon
  become: yes
  systemd:
    name: kubelet
    enabled: yes
    state: restarted
    daemon_reload: yes
